


artifacts_root : artifacts


data_ingestion:
  root_dir : artifacts/data_ingestion
  source_URL : 'https://github.com/MadanuAugustin/BreastCancerClassification_with_MLflow_ANN/raw/main/Notebook/archive%20(2).zip'
  local_data_file : artifacts/data_ingestion/raw-data.zip
  unzip_dir : artifacts/data_ingestion